import {
  collection,
  doc,
  getDocs,
  setDoc,
  updateDoc,
  query,
  where,
  addDoc,
} from 'firebase/firestore';
import { db, auth } from '../firebase/config';
import { Department, Designation } from '../../types/organization';

enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
  };
}

function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth?.currentUser?.uid,
      email: auth?.currentUser?.email,
      emailVerified: auth?.currentUser?.emailVerified,
      isAnonymous: auth?.currentUser?.isAnonymous,
    },
    operationType,
    path,
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

// FETCH DEPARTMENTS
export const fetchDepartments = async (): Promise<Department[]> => {
  const path = 'departments';
  try {
    const qSnap = await getDocs(collection(db, path));
    const depts: Department[] = [];
    qSnap.forEach((docSnap) => {
      const data = docSnap.data();
      depts.push({
        id: docSnap.id,
        name: data.name || '',
        description: data.description || '',
        active: data.active !== false,
        createdAt: data.createdAt || '',
        updatedAt: data.updatedAt || '',
      });
    });
    return depts;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, path);
    return [];
  }
};

// ADD DEPARTMENT
export const addDepartment = async (name: string, description: string): Promise<string> => {
  const path = 'departments';
  try {
    const now = new Date().toISOString();
    // Use an ID generated by Firestore or standard custom ID
    const docRef = doc(collection(db, path));
    const id = docRef.id;
    await setDoc(docRef, {
      id,
      name: name.trim(),
      description: description.trim(),
      active: true,
      createdAt: now,
      updatedAt: now,
    });
    return id;
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, path);
    return '';
  }
};

// UPDATE DEPARTMENT
export const updateDepartment = async (id: string, name: string, description: string): Promise<void> => {
  const path = `departments/${id}`;
  try {
    const now = new Date().toISOString();
    const docRef = doc(db, 'departments', id);
    await updateDoc(docRef, {
      name: name.trim(),
      description: description.trim(),
      updatedAt: now,
    });
  } catch (error) {
    handleFirestoreError(error, OperationType.UPDATE, path);
  }
};

// TOGGLE DEPARTMENT ACTIVE STATUS
export const toggleDepartmentActive = async (id: string, currentActive: boolean): Promise<void> => {
  const path = `departments/${id}`;
  try {
    const now = new Date().toISOString();
    const docRef = doc(db, 'departments', id);
    await updateDoc(docRef, {
      active: !currentActive,
      updatedAt: now,
    });
  } catch (error) {
    handleFirestoreError(error, OperationType.UPDATE, path);
  }
};

// FETCH DESIGNATIONS
export const fetchDesignations = async (): Promise<Designation[]> => {
  const path = 'designations';
  try {
    const qSnap = await getDocs(collection(db, path));
    const desigs: Designation[] = [];
    qSnap.forEach((docSnap) => {
      const data = docSnap.data();
      desigs.push({
        id: docSnap.id,
        name: data.name || '',
        description: data.description || '',
        active: data.active !== false,
        createdAt: data.createdAt || '',
        updatedAt: data.updatedAt || '',
      });
    });
    return desigs;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, path);
    return [];
  }
};

// ADD DESIGNATION
export const addDesignation = async (name: string, description: string): Promise<string> => {
  const path = 'designations';
  try {
    const now = new Date().toISOString();
    const docRef = doc(collection(db, path));
    const id = docRef.id;
    await setDoc(docRef, {
      id,
      name: name.trim(),
      description: description.trim(),
      active: true,
      createdAt: now,
      updatedAt: now,
    });
    return id;
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, path);
    return '';
  }
};

// UPDATE DESIGNATION
export const updateDesignation = async (id: string, name: string, description: string): Promise<void> => {
  const path = `designations/${id}`;
  try {
    const now = new Date().toISOString();
    const docRef = doc(db, 'designations', id);
    await updateDoc(docRef, {
      name: name.trim(),
      description: description.trim(),
      updatedAt: now,
    });
  } catch (error) {
    handleFirestoreError(error, OperationType.UPDATE, path);
  }
};

// TOGGLE DESIGNATION ACTIVE STATUS
export const toggleDesignationActive = async (id: string, currentActive: boolean): Promise<void> => {
  const path = `designations/${id}`;
  try {
    const now = new Date().toISOString();
    const docRef = doc(db, 'designations', id);
    await updateDoc(docRef, {
      active: !currentActive,
      updatedAt: now,
    });
  } catch (error) {
    handleFirestoreError(error, OperationType.UPDATE, path);
  }
};
